### ISSUE TITLE
How to query on number of total tests, and number of wipped tests?

### ISSUE THREAD

**Issue by cartoloupe** [enkessler/cql#8]
I read through the documentation, but could not find how to query for number of total tests and number of wipped tests.

**Comment by cartoloupe** [comment]
Update: read the examples some more, found I could do this:

```ruby
#!/usr/bin/env ruby
require 'cql'
require 'pry'

cql_repo = CQL::Repository.new 'features'

total_tests = cql_repo.query do
  select name
  from scenarios
end.size

wipped_tests = cql_repo.query do
  select name
  from scenarios
  with lambda { |scenario| scenario.tags.include?('@wip') }
end.size

puts "#{wipped_tests}/#{total_tests}"
```

:+1:

**Comment by enkessler** [comment]
For your test counting case, that query will only pick up a Scenario. If you want to find all of your tests, then you will want to include both types in your query. Like so:

    total_tests = cql_repo.query do
      select
      from scenarios, outlines
    end

    puts "total tests: #{total_tests.count}"

If you further wanted to know about individual test executions, then you would need to break down the outlines into their rows:

    total_tests = cql_repo.query do
      select :self
      as test_cases
      from scenarios, outlines
      transform :self => lambda { |test|
                  if test.is_a?(CukeModeler::Outline)
                    # Outlines are many test cases from one template
                    test.examples.reduce(0) { |sum, example| sum += example.rows.count }
                  else
                    # Scenarios are just a single test case
                    1
                  end
                }
    end

    puts "total_tests: #{total_tests.collect { |result| result['test_cases'] }.reduce(:+)}"


Finally, be aware that #tags only return tags that are directly attached to the test. #all_tags is the method that you would want to use if you want to pick up tags that tests inherit from the Feature level as well.

**Comment by cartoloupe** [comment]
Thank you; this was very helpful.
